version: '3.6.3'
services:
  db:
    image: mariadb:11.2.4
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=kitodo
      - MYSQL_USER=kitodo
      - MYSQL_PASSWORD=kitodo
    volumes:
      - ./database:/var/lib/mysql
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    environment:
      - cluster.name=kitodo
      - node.name=kitodo-1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=kitodo-1
      - cluster.initial_master_nodes=kitodo-1
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KITODO_VERSION=${KITODO_VERSION}
    image: kitodo/production:${KITODO_VERSION}
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_ADDR=db
      - ELASTIC_ADDR=elastic
      - CONFIG_PATH=${PWD}/config
    env_file:
      - .env
    volumes:
      - ./config:/usr/local/kitodo
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - elastic
  ocrd:
    image: ocrd/all:maximum
